/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zw_demo_ndkmutimoduledemo_jnidemo_Demo */

#ifndef _Included_com_zw_demo_ndkmutimoduledemo_jnidemo_Demo
#define _Included_com_zw_demo_ndkmutimoduledemo_jnidemo_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zw_demo_ndkmutimoduledemo_jnidemo_Demo
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_zw_demo_ndkmutimoduledemo_jnidemo_Demo_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
